---
- name: Configure KVM Host for Libvirt
  hosts: kvm_host
  # 'ansible_connection=local' in inventory handles running this locally
  # If it's a remote host, Ansible will SSH as normal.
  become: true
  gather_facts: true

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install KVM/libvirt packages and Python bindings
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
          - python3-libvirt   # For community.libvirt
          - libguestfs-tools  # For virt-customize
        state: present

    - name: Ensure libvirtd service is running and enabled
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Add current user to 'libvirt' group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: libvirt
        append: true