---
- name: Configure Local Debian Host for KVM/Libvirt
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install KVM/libvirt packages
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
          - python3-libvirt   # Required for community.libvirt Ansible collection
          - libguestfs-tools  # Useful for image customization (like virt-customize)
          - virtinst          # For the virt-install tool
        state: present
      register: install_packages

    - name: Ensure libvirtd service is running and enabled
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Add current user to 'libvirt' group
      ansible.builtin.user:
        name: "{{ ansible_user | default(lookup('env', 'USER')) }}"
        groups: libvirt
        append: true
      # NOTE: User needs to log out/in after this task for group changes to take effect.
      # You can add a `pause` task and note this to the user.

    - name: Check for successful installation
      ansible.builtin.command: virsh list --all
      register: virsh_check
      changed_when: false
      failed_when: "'virsh' not in virsh_check.stdout"
      
    - name: Display KVM installation status
      ansible.builtin.debug:
        msg: "KVM/Libvirt installation complete. You may need to log out and log back in for group changes to take effect."