---
- name: Teardown Kubernetes VMs AND Uninstall KVM Host Setup
  hosts: kvm_host
  become: true
  gather_facts: false

  vars:
    vm_names:
      - k8s-master
      - k8s-worker-1
      - k8s-worker-2
    kvm_packages:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - python3-libvirt
      - libguestfs-tools
      - virtinst
    disk_base_path: "{{ kvm_disk_path | default('/var/lib/libvirt/images') }}"
    cloud_image_file: "{{ cloud_image_file | default('debian-12-genericcloud-amd64.qcow2') }}"

  tasks:
    - name: Destroy and undefine KVM domains (VMs)
      community.libvirt.virt:
        name: "{{ item }}"
        command: undefine 
        state: absent     
        delete_volumes: true
      loop: "{{ vm_names }}"
      ignore_errors: true 

    - name: Remove associated disk image files
      ansible.builtin.file:
        path: "{{ disk_base_path }}/{{ item }}.qcow2" 
        state: absent
      loop: "{{ vm_names }}"
      ignore_errors: true

    - name: Remove base cloud image
      ansible.builtin.file:
        path: "{{ disk_base_path }}/{{ cloud_image_file }}"
        state: absent
      ignore_errors: true

    - name: Remove current user from 'libvirt' group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: libvirt
        append: false # This means 'remove'
      ignore_errors: true # Ignore if user is not in group

    - name: Stop and disable libvirtd service
      ansible.builtin.systemd:
        name: libvirtd
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Uninstall KVM, libvirt, and all related packages
      ansible.builtin.apt:
        name: "{{ kvm_packages }}"
        state: absent
        autoremove: true # Removes dependencies
        purge: true      # Removes config files

    - name: Cleanup Complete Message
      ansible.builtin.debug:
        msg: "Full cleanup successful. VMs, disks, and all KVM packages have been removed."